---
title: "Bayesian Chi Squared Procedures"
author: "Alisa Krasilnikov"
format: html
embed-resources: true
editor: source
---

# References: 
 
1. Doing Bayesian data analysis:
 - Chapter 24 - Count Predicted Variables
 - Exercise 24.3 

2. https://www.flutterbys.com.au/stats/tut/tut11.2b.html


https://www.kaggle.com/datasets/kritirathi/indian-food-dataset-with

```{r}
library(brms)
library(tidybayes)
library(bayesplot)
library(dplyr)
```

```{r}
food <- read.csv(here::here("Ifood_new.csv"))
#food <- read.csv("C:\\Users\\Geetha\\Downloads\\archive (1)\\Ifood_new.csv")
indfood <- food |> 
  filter(flavor_profile != "-1")
```


## Prior Predictive Distribution

We believe the non-vegetarian food will be spicier than the vegetarian food and that the vegetarian food will be sweeter than the non-vegetarian food.

```{r}
summary(food)
food
```

```{r}
indfood <-indfood |> mutate(dum_diet = if_else(diet == "vegetarian", 1, 2))
```

```{r}
fit <- brm(data = indfood,
           family = gaussian(),
           dum_diet ~ 1 + flavor_profile,
           iter = 3500,
           warmup = 1000,
           chains = 4,
           refresh = 0)
```

```{r}
n_rep = 10000

# value of x
x = 20

# simulate parameters from prior distribution
beta0 = rnorm(n_rep, 0, 1)
beta1 = rnorm(n_rep, 1, 0.5)
sigma = rexp(n_rep, 1 / 5)

# simulate values of percent body fat based on assumptions of regression model
y = rnorm(n_rep, beta0 + beta1 * x, sigma)

hist(y, xlab = "Prior predicted PBF(%) for BMI of 20 kg/m^2",
     breaks = 100,
     col = bayes_col["prior_predict"])
```

